create table users(

    id bigint generated by default as identity ,
    username varchar(50) unique not null,
    email varchar(100) unique not null ,
    password_hash varchar not null,
    role varchar not null,
    created_at timestamp not null ,
    avatar_url varchar,
    subscription_status boolean not null,
    primary key (id)
);

create table artists(

    id bigint generated by default as identity ,
    artist_name varchar(50) not null unique ,
    photo_url varchar,
    bio varchar(500),
    primary key (id)

);

create table albums(

    id bigint generated by default as identity ,
    title varchar(50) not null,
    photo_url varchar,
    release_date timestamp not null,
    artist_id bigint not null references artists(id),
    primary key (id)
);

create table genres(
    id bigint generated by default as identity ,
    title varchar(100) unique not null,
    primary key (id)
);

create table tracks(

    id bigint generated by default as identity ,
    artist_id bigint not null references artists(id),
    album_id bigint not null references albums(id),
    genre_id bigint references genres(id),
    title varchar(50) not null,
    duration integer not null ,
    audio_url varchar not null unique ,
    cover_url varchar not null ,
    play_count bigint default 0,
    release_date timestamp  not null,
    primary key (id)

);

create table playlists(

    id bigint generated by default as identity ,
    user_id bigint not null references users(id),
    name varchar(50) not null,
    is_favorite boolean not null,
    created_at timestamp not null,
    primary key (id)

);

create table playlist_tracks(

    id bigint generated by default as identity ,
    playlist_id bigint not null references playlists(id),
    track_id bigint not null references tracks(id),
    position integer not null,
    primary key (id)
);

create table refresh_tokens(
    id bigint generated by default as identity,
    user_id bigint not null references users(id),
    token varchar(2048) not null unique,
    expires_at timestamp not null,
    primary key (id)
);

create table user_artist_favorites(
    id bigint generated by default as identity,
    user_id bigint not null references users(id),
    artist_id bigint not null references artists(id),
    created_at timestamp not null,
    primary key (id),
    constraint uk_user_artist unique (user_id, artist_id)
);

