create table users(

    id bigint generated by default as identity ,
    username varchar(50) unique not null,
    email varchar(100) unique not null ,
    password_hash varchar not null,
    role varchar not null,
    created_at timestamp not null ,
    avatar_url varchar,
    subscription_status boolean not null,
    primary key (id)
);

create table artists(

    id bigint generated by default as identity ,
    artist_name varchar(50) not null unique ,
    photo_url varchar,
    bio varchar(500),
    primary key (id)

);

create table albums(

    id bigint generated by default as identity ,
    title varchar(50) not null,
    album_photo_url varchar,
    release_date timestamp not null,
    artist_id bigint references artists(id),
    primary key (id)
);

create table genres(
    id bigint generated by default as identity ,
    title varchar(50),
    primary key (id)
);

create table tracks(

    id bigint generated by default as identity ,
    artist_id bigint references artists(id),
    album_id bigint references albums(id),
    genre_id bigint references genres(id),
    title varchar(50) not null,
    duration integer not null ,
    audio_url varchar not null unique ,
    cover_url varchar not null ,
    play_count bigint default 0,
    release_date timestamp  not null,
    primary key (id)

);

create table playlists(

    id bigint generated by default as identity ,
    user_id bigint references users(id),
    name varchar(50) not null,
    is_favorite boolean not null,
    created_at timestamp not null,
    primary key (id)

);

create table playlist_tracks(

    id bigint generated by default as identity ,
    playlist_id bigint references playlists(id),
    track_id bigint references tracks(id),
    primary key (id)
);

